### ISSUE TITLE
Spam or just crazy people?

### ISSUE THREAD

**Issue by hbclake** [techxlab/www.techxlab.org#2]
@jldec 

We received two sign ups, back-to-back, of the same message coming from different email addresses. Is this a robot or just a crazy person? Judging by the phone number, I'm guessing they are coming from Nigeria, so...

Name: johnson
Email: drobaspellhome@gmail.com
Message:
i Its a well-known fact that Illuminati consist of
 Multi Millionaires, Billionaires who have major
influence regarding most global affairs,
including
the planning of a New World Order. Many world
leaders, Presidents, Prime Ministers, royalty
and
senior executives of major Fortune 500
companies
are members of Illuminati.
join a secret cabal of mysterious forces and
become
rich with boundless
measures of wealth in your company or any
given
business,the great
illuminati can make you rich forever email us now at jhnsnadam@gmail.com or
call +2348165692852

id: gbq4a6u
created: 2016-02-16 07:31

Name: johnson
Email: murphyehizokhale@gmail.com
Message:
i Its a well-known fact that Illuminati consist of
 Multi Millionaires, Billionaires who have major
influence regarding most global affairs,
including
the planning of a New World Order. Many world
leaders, Presidents, Prime Ministers, royalty
and
senior executives of major Fortune 500
companies
are members of Illuminati.
join a secret cabal of mysterious forces and
become
rich with boundless
measures of wealth in your company or any
given
business,the great
illuminati can make you rich forever email us now at jhnsnadam@gmail.com or
call +2348165692852

id: gbs97d8
created: 2016-02-16 08:31

**Comment by jldec** [comment]
hard to tell the difference :)
just delete it - if it becomes a problem we'll find a way to block.
